### PR TITLE
Core and Views - Fixed warnings

### PR DESCRIPTION
**Pull request by EmreTech**
Originally a fix for #155 

This Pull Request aims to fix some small minor warnings that can cause a lot of scrolling if the build failed.

### CODE REVIEW

**Comment by natinusala** [comment]
Can you run clang-format on this please? Using the script in the repo

**Comment by natinusala** [comment]
(also thanks for the PR!)

**Comment by EmreTech** [comment]
Sure!

**Comment by EmreTech** [comment]
Okay, why is there a file named `-` after running that clang-format script?

**Comment by natinusala** [comment]
I don't know what did you run exactly?

**Comment by EmreTech** [comment]
I ran `./scripts/format.sh --fix` and it said this after the `patching file *insert file here*`:

```
Hunk #1 FAILED at 19.
1 out of 1 hunk FAILED -- saving rejects to file -
```

**Comment by natinusala** [comment]
You succeeded to keep everything but the important part of the error 
message, can I see it entirely?

**Comment by p-sam** [comment]
I'm not sure how you would run into conflicts with yourself (essentially the script is generating a patch file of the format changes, and failing to apply it) but you may just have edited the file while the script was running (you or your IDE)

**Comment by EmreTech** [comment]
Here's the full output from the command:
```
patching file library/include/borealis/core/font.hpp
patching file library/include/borealis/core/util.hpp
patching file library/include/borealis/core/input.hpp
patching file library/include/borealis/views/rectangle.hpp
patching file library/include/borealis/views/button.hpp
patching file library/lib/platforms/switch/switch_audio.cpp
patching file library/lib/core/util.cpp
Hunk #1 FAILED at 19.
1 out of 1 hunk FAILED -- saving rejects to file -
patching file library/lib/views/button.cpp
patching file library/lib/views/image.cpp
patching file library/lib/views/label.cpp
```

**Comment by EmreTech** [comment]
> I'm not sure how you would run into conflicts with yourself (essentially the script is generating a patch file of the format changes, and failing to apply it) but you may just have edited the file while the script was running (you or your IDE)

That could be the case, I think I might've forgotten to close the file in VS Code

**Comment by natinusala** [comment]
Yeah I encountered the same issue today while working on the library. 
util.cpp has different line endings (CRLF) and the patch fails. Open it in 
vscode and convert the line endings to LF then run clang format again

**Comment by EmreTech** [comment]
Alright, that actually worked.

**Comment by EmreTech** [comment]
> Also the script should output the rejects to stdout (not to a file named "-")

Yeah, that doesn't seem normal...
I downloaded clang-format-8 from brew, maybe it's slightly broken?

**Pull request merged**
