### PR TITLE
Describable mixin

### LINKED ISSUE #158: Describable mixin
Move the `describe` method to its own `Describable` class to make it reusable

### PR DESCRIPTION
**Pull request by maxnatamo**
Fixes #158 

Also, excuse the typo in the commit message.

### CODE REVIEW

**Comment by natinusala** [comment]
Hello, thanks for the PR!

What you did is an interface, not a mixin.

Also for the commit message can you please reword it? Thanks

**Comment by maxnatamo** [comment]
I've amended the commit. Whether an interface is fine or it has to be a mixin, is up to you.

**Comment by natinusala** [comment]
The point is to do a mixin, not an interface :P

**Comment by EmmmaTech** [comment]
Alright, so, I recommend you search up what a `mixin` is before you make this PR. It's not just an inherited class, it's a lot more.

Edit: I searched on Google, and found this, which contains many examples and definitions for mixins: https://stackoverflow.com/questions/533631/what-is-a-mixin-and-why-are-they-useful

**Pull request closed without merging**
